#!/bin/sh
#
# Simple build script that builds & copies pi-init2, as well as "appliance"
# files onto Raspberry Pi.
#
# Works for me on an Ubuntu system where a Raspberry Pi appears under
# /media/mattbee/boot but you may need to adjust.

export GOPATH=`pwd`
export GOOS=linux
export GOARCH=arm

FILES="boot/*"
TARGET_DIR="/media/takd/boot"
#TARGET_DIR="/Volumes/boot"

go build -o boot/pi-init2 pi-init2 && \
  mv "${TARGET_DIR}/cmdline.txt" "${TARGET_DIR}/cmdline.txt.orig" && \
  cp -a ${FILES} ${TARGET_DIR} && \
  umount ${TARGET_DIR}

if [ "$1" != "" ]; then
  echo "set hostname to $1"
  echo "$1" > ${TARGET_DIR}/hostname
fi

printf "hostname: "
cat ${TARGET_DIR}/hostname
