#!/bin/bash

#### Wifi Setup (WPA Supplicant)
##  Replaces the magic of https://github.com/RPi-Distro/raspberrypi-net-mods/blob/master/debian/raspberrypi-net-mods.service
##  See: https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md
cat > /etc/wpa_supplicant/wpa_supplicant.conf << EOF
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=US

network={
    ssid="bruno"
    psk="I didn't commit my real password to github"
}
EOF
chmod 600 /etc/wpa_supplicant/wpa_supplicant.conf
wpa_cli -i wlan0 reconfigure

#### SSH Daemon Setup
##  Replaces the magic of https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/master/debian/raspberrypi-sys-mods.sshswitch.service
##  See also: https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/master/debian/raspberrypi-sys-mods.regenerate_ssh_host_keys.service
update-rc.d ssh enable && invoke-rc.d ssh start
dd if=/dev/hwrng of=/dev/urandom count=1 bs=4096
rm -f -v /etc/ssh/ssh_host_*_key*
/usr/bin/ssh-keygen -A -v

#### Get SSH keys for authentication
github_user=RichardBronosky
echo -e "GET http://github.com HTTP/1.0\n\n" | nc github.com 80 > /dev/null 2>&1
if [ $? -eq 0 ]; then
  (
    umask 077
    mkdir -p /home/pi/.ssh
    curl -sSL https://github.com/${github_user}.keys >> /home/pi/.ssh/authorized_keys
    chown -R $(id -u pi):$(id -g pi) /home/pi/.ssh
  )
  sed -i 's|[#]*PasswordAuthentication yes|PasswordAuthentication no|g' /etc/ssh/sshd_config
else
  echo "Won't install ssh keys, github.com couldn't be reached."
fi

#### Install some packages
apt install -y git vim tmux

#### Do other stuff
# This is just here to help verify that it worked
sudo -u pi touch /home/pi/.bash_aliases
echo "alias ll='ls -la'" | tee -a /home/pi/.bash_aliases | tee -a /root/.bashrc > /dev/null
