#!/bin/bash -eux

wait_for_inet(){
  msg='Waiting for internet connection.'
  until nc -zw2 8.8.8.8 53; do
    echo -n $msg;
    msg=' .';
  done
  if [[ $msg = ' .' ]]; then echo; fi
}

#### Wifi Setup (WPA Supplicant)
##  Replaces the magic of https://github.com/RPi-Distro/raspberrypi-net-mods/blob/master/debian/raspberrypi-net-mods.service
##  See: https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md
cat > /etc/wpa_supplicant/wpa_supplicant.conf << EOF
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=US

network={
    ssid="bruno"
    psk="I didn't commit my real password to github"
}
EOF
chmod 600 /etc/wpa_supplicant/wpa_supplicant.conf
until wpa_cli -i wlan0 reconfigure; do
  echo "Failed to reconfigure wlan0 with wpa_cli."
  echo "Restarting dhcpcd with systemctl."
  systemctl restart dhcpcd || true
done

#### SSH Daemon Setup
##  Replaces the magic of https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/master/debian/raspberrypi-sys-mods.sshswitch.service
##  See also: https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/master/debian/raspberrypi-sys-mods.regenerate_ssh_host_keys.service
update-rc.d ssh enable && invoke-rc.d ssh start
dd if=/dev/hwrng of=/dev/urandom count=1 bs=4096
rm -f -v /etc/ssh/ssh_host_*_key*
/usr/bin/ssh-keygen -A -v

#### Get SSH keys for authentication
github_user=RichardBronosky
wait_for_inet
echo -e "GET http://github.com HTTP/1.0\n\n" | nc github.com 80 > /dev/null 2>&1
if [ $? -eq 0 ]; then
  (
    umask 077
    mkdir -p /home/pi/.ssh
    curl -sSL https://github.com/${github_user}.keys >> /home/pi/.ssh/authorized_keys
    chown -R $(id -u pi):$(id -g pi) /home/pi/.ssh
  )
  sed -i 's|[#]*PasswordAuthentication yes|PasswordAuthentication no|g' /etc/ssh/sshd_config
else
  echo "Won't install ssh keys, github.com couldn't be reached."
fi

#### Install some packages
apt update
apt install -y git vim tmux

#### Do other stuff
sudo -u pi touch /home/pi/.bashrc
( tee -a /home/pi/.bashrc | tee -a /root/.bashrc > /dev/null ) << 'EOF'

alias ll='ls -la'
ptree(){ ps auxf | awk -v cmd="$1" 'BEGIN{"ps -o ppid= $$" | getline pid} $0 !~ "\_" {p=0} $0 ~ cmd && $2 != pid {p=1} p==1{print}' | less -SEX; }
EOF
sudo -u pi touch /home/pi/.bash_history
( tee -a /home/pi/.bash_history | tee -a /root/.bash_history > /dev/null ) << 'EOF'
ptree pi-init2-run-parts.sh
find /boot/run-once.d/
tail -f /boot/run-once.d/completed/logfile-*
ptree pi-init2-run-parts.sh; find /boot/run-once.d/; tail -f /boot/run-once.d/completed/logfile-*
EOF
