#!/bin/bash

# Remove this file if you want to re-run the setup
#
if [ -f /boot/pi-install.done ] ; then
  exit 0
fi

touch /boot/ssh
raspi-config nonint do_hostname "$(cat /boot/hostname)"

touch /boot/pi-install.done

exit 0
